name: Docker Push katpool-app image

on:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: get repository name
        run: |
          echo "REPOSITORY_NAME=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository }}'

      - name: Extract Branch Name
        id: extract_branch
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Docker Login
        run: echo "${{ secrets.GB_KATPOOL_TOKEN }}" | docker login ${{ env.REGISTRY }} --username argonmining --password-stdin

      - name: Docker Build with Cache
        env:
          IMAGE_NAME: ${{ env.REPOSITORY_NAME }}:beta-v1.0.2-${{ env.branch_name }}
          CACHE_FROM: ${{ env.REGISTRY }}/${{ env.REPOSITORY_NAME }}:buildcache
        run: |
          docker buildx build \
            --cache-from=type=registry,ref=${{ env.CACHE_FROM }} \
            --cache-to=type=registry,ref=${{ env.CACHE_FROM }},mode=max \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            --push \
            .

      - name: Docker Build DB Backup with Cache
        env:
          IMAGE_NAME: ${{ env.REPOSITORY_NAME }}-db-backup:beta-v1.0.2-${{ env.branch_name }}
          CACHE_FROM: ${{ env.REGISTRY }}/${{ env.REPOSITORY_NAME }}-db-backup:buildcache
        run: |
          docker buildx build \
            --cache-from=type=registry,ref=${{ env.CACHE_FROM }} \
            --cache-to=type=registry,ref=${{ env.CACHE_FROM }},mode=max \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            --push \
            -f backup/Dockerfile \
            backup/